In [1]:
import pandas as pd

In [2]:
data= pd.read_csv("../PythonProject/Airbnb_Open_Data.csv",low_memory=False)

In [3]:
data.head()

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN

In [4]:
data.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count', 'availability',
       'house_rules', 'license'],
      dtype='object')

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 26 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102599 non-null  int64
 1   NAME                            102349 non-null  object
 2   host id                         102599 non-null  int64
 3   host_identity_verified          102310 non-null  object
 4   host name                       102193 non-null  object
 5   neighbourhood group             102570 non-null  object
 6   neighbourhood                   102583 non-null  object
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   country                         102067 non-null  object
 10  country code                    102468 non-null  object
 11  instant_bookable                102494 non-null  object
 12  cancellation_policy             102523 non-null  object
 13  room type                       102599 non-null  object
 14  Construction year               102385 non-null  float64
 15  price                           102352 non-null  object
 16  service fee                     102326 non-null  object
 17  minimum nights                  102190 non-null  float64
 18  number of reviews               102416 non-null  float64
 19  last review                     86706 non-null   object
 20  reviews per month               86720 non-null   float64
 21  review rate number              102273 non-null  float64
 22  calculated host listings count  102280 non-null  float64
 23  availability                    102151 non-null  float64
 24  house_rules                     50468 non-null   object
 25  license                         2 non-null       object
dtypes: float64(9), int64(2), object(15)
memory usage: 20.4+ MB

In [6]:
# 1. DELETING REDUNDANT COLUMNS
columns_keep = ['NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review']

columns_drop = ['id','reviews per month',
       'review rate number', 'calculated host listings count', 'availability',
       'house_rules', 'license']

In [7]:
len(columns_keep)

19

In [8]:
len(columns_drop)

7

In [9]:
#Ist Method: Filtering Data
df = data[columns_keep]  # assign to new data frame

In [10]:
#data.shape
df

,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/2021
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/2022
2,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,True,flexible,Private room,2005.0,$620,$124,3.0,0.0,NaN
3,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,True,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0,7/5/2019
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,11/19/2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,US,False,flexible,Private room,2003.0,$844,$169,1.0,0.0,NaN
102595,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,US,True,moderate,Private room,2016.0,$837,$167,1.0,1.0,7/6/2015
102596,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,US,True,moderate,Private room,2009.0,$988,$198,3.0,0.0,NaN
102597,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,US,True,strict,Entire home/apt,2015.0,$546,$109,2.0,5.0,10/11/2015
102598,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,US,False,flexible,Entire home/apt,2010.0,"$1,032",$206,1.0,0.0,NaN

In [11]:
# 2nd Method: dropping columns

data.drop(columns = ["license"])  # drop license column . but we still have license in original data frame. so we use inplace =True

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,price,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability,house_rules
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$966,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$142,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$620,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and..."
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$368,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$204,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,$844,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,$837,$167,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,$988,$198,3.0,0.0,NaN,NaN,5.0,1.0,342.0,NaN
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,$546,$109,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,"$1,032",$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0,NaN

In [12]:
# To drop more than one column 

data.drop(columns = columns_drop, inplace =True)

In [13]:
data.shape   # so now when we call data , we will have 19 columns instead of 26

(102599, 19)

In [14]:
# 2. RENAMING THE COLUMNS  - We want to rename the column NAME to lower case . we will create dictionary

data.rename(columns ={"NAME" : "Name"}, inplace =True)

In [15]:
data

,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/2021
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/2022
2,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,True,flexible,Private room,2005.0,$620,$124,3.0,0.0,NaN
3,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,True,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0,7/5/2019
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,11/19/2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,US,False,flexible,Private room,2003.0,$844,$169,1.0,0.0,NaN
102595,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,US,True,moderate,Private room,2016.0,$837,$167,1.0,1.0,7/6/2015
102596,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,US,True,moderate,Private room,2009.0,$988,$198,3.0,0.0,NaN
102597,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,US,True,strict,Entire home/apt,2015.0,$546,$109,2.0,5.0,10/11/2015
102598,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,US,False,flexible,Entire home/apt,2010.0,"$1,032",$206,1.0,0.0,NaN

In [16]:
# To modify all the column names in one step i.e if i want all the columns to uppercase use upper() or lowercwse use lower()

data.columns

Index(['Name', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review'],
      dtype='object')

In [17]:
for i in data.columns:
    print(i.upper())

NAME
HOST ID
HOST_IDENTITY_VERIFIED
HOST NAME
NEIGHBOURHOOD GROUP
NEIGHBOURHOOD
LAT
LONG
COUNTRY
COUNTRY CODE
INSTANT_BOOKABLE
CANCELLATION_POLICY
ROOM TYPE
CONSTRUCTION YEAR
PRICE
SERVICE FEE
MINIMUM NIGHTS
NUMBER OF REVIEWS
LAST REVIEW

In [18]:
new_column_names = []
for i in data.columns:
    new_column_names.append(i.upper())

In [19]:
new_column_names

['NAME',
 'HOST ID',
 'HOST_IDENTITY_VERIFIED',
 'HOST NAME',
 'NEIGHBOURHOOD GROUP',
 'NEIGHBOURHOOD',
 'LAT',
 'LONG',
 'COUNTRY',
 'COUNTRY CODE',
 'INSTANT_BOOKABLE',
 'CANCELLATION_POLICY',
 'ROOM TYPE',
 'CONSTRUCTION YEAR',
 'PRICE',
 'SERVICE FEE',
 'MINIMUM NIGHTS',
 'NUMBER OF REVIEWS',
 'LAST REVIEW']

In [20]:
new_dataframe_to_modify =data.copy()

In [21]:
new_dataframe_to_modify.columns = new_column_names

In [22]:
new_dataframe_to_modify

,NAME,HOST ID,HOST_IDENTITY_VERIFIED,HOST NAME,NEIGHBOURHOOD GROUP,NEIGHBOURHOOD,LAT,LONG,COUNTRY,COUNTRY CODE,INSTANT_BOOKABLE,CANCELLATION_POLICY,ROOM TYPE,CONSTRUCTION YEAR,PRICE,SERVICE FEE,MINIMUM NIGHTS,NUMBER OF REVIEWS,LAST REVIEW
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/2021
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/2022
2,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,True,flexible,Private room,2005.0,$620,$124,3.0,0.0,NaN
3,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,True,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0,7/5/2019
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,11/19/2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,US,False,flexible,Private room,2003.0,$844,$169,1.0,0.0,NaN
102595,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,US,True,moderate,Private room,2016.0,$837,$167,1.0,1.0,7/6/2015
102596,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,US,True,moderate,Private room,2009.0,$988,$198,3.0,0.0,NaN
102597,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,US,True,strict,Entire home/apt,2015.0,$546,$109,2.0,5.0,10/11/2015
102598,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,US,False,flexible,Entire home/apt,2010.0,"$1,032",$206,1.0,0.0,NaN

In [23]:
new_dataframe_to_modify.columns

Index(['NAME', 'HOST ID', 'HOST_IDENTITY_VERIFIED', 'HOST NAME',
       'NEIGHBOURHOOD GROUP', 'NEIGHBOURHOOD', 'LAT', 'LONG', 'COUNTRY',
       'COUNTRY CODE', 'INSTANT_BOOKABLE', 'CANCELLATION_POLICY', 'ROOM TYPE',
       'CONSTRUCTION YEAR', 'PRICE', 'SERVICE FEE', 'MINIMUM NIGHTS',
       'NUMBER OF REVIEWS', 'LAST REVIEW'],
      dtype='object')

In [24]:
# 3. DROPPING DUPLICATES
data

,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/2021
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/2022
2,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,True,flexible,Private room,2005.0,$620,$124,3.0,0.0,NaN
3,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,True,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0,7/5/2019
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,11/19/2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,US,False,flexible,Private room,2003.0,$844,$169,1.0,0.0,NaN
102595,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,US,True,moderate,Private room,2016.0,$837,$167,1.0,1.0,7/6/2015
102596,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,US,True,moderate,Private room,2009.0,$988,$198,3.0,0.0,NaN
102597,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,US,True,strict,Entire home/apt,2015.0,$546,$109,2.0,5.0,10/11/2015
102598,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,US,False,flexible,Entire home/apt,2010.0,"$1,032",$206,1.0,0.0,NaN

In [25]:
data.duplicated()   # gets the value in True or False

0         False
1         False
2         False
3         False
4         False
          ...
102594     True
102595     True
102596     True
102597     True
102598     True
Length: 102599, dtype: bool

In [26]:
#To see the total amount of duplicated use sum()

In [27]:

#data.duplicated().head()
#data.duplicated().tail()

In [28]:
data.duplicated().value_counts()

False    102058
True        541
Name: count, dtype: int64

In [29]:
data.duplicated().sum()   # it will give duplicated counts

541

In [30]:
# to drop the duplicated rows, we have a method name drop_duplicates()

data.drop_duplicates()

,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/2021
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/2022
2,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,True,flexible,Private room,2005.0,$620,$124,3.0,0.0,NaN
3,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,True,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0,7/5/2019
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,11/19/2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102053,Cozy bright room near Prospect Park,77326652202,unconfirmed,Mariam,Brooklyn,Flatbush,40.64945,-73.96108,United States,US,True,moderate,Private room,NaN,$696,NaN,7.0,12.0,3/27/2019
102054,Private Bedroom with Amazing Rooftop View,45936254757,verified,Trey,Brooklyn,Bushwick,40.69872,-73.92718,United States,US,False,flexible,Private room,NaN,$909,NaN,1.0,19.0,8/31/2017
102055,Pretty Brooklyn One-Bedroom for 2 to 4 people,23801060917,verified,Michael,Brooklyn,Bedford-Stuyvesant,40.67810,-73.90822,United States,US,True,moderate,Entire home/apt,NaN,$387,NaN,2.0,50.0,6/26/2019
102056,Room & private bathroom in historic Harlem,15593031571,unconfirmed,Shireen,Manhattan,Harlem,40.81248,-73.94317,United States,US,True,strict,Private room,NaN,$848,NaN,2.0,0.0,NaN
102057,Rosalee Stewart,93578954226,verified,Stanley,Manhattan,Harlem,40.81315,-73.94747,United States,US,False,flexible,Entire home/apt,2011.0,"$1,128",NaN,4.0,22.0,6/15/2019

In [31]:
# Two ways 
#data = data.drop_duplicates()   OR 

data.drop_duplicates(inplace = True)

In [32]:
data.duplicated().sum()   # it will give duplicated counts

0

In [33]:
# 4. REMOVE THE NaN values from the dataset

data

,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/2021
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/2022
2,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,True,flexible,Private room,2005.0,$620,$124,3.0,0.0,NaN
3,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,True,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0,7/5/2019
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,11/19/2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102053,Cozy bright room near Prospect Park,77326652202,unconfirmed,Mariam,Brooklyn,Flatbush,40.64945,-73.96108,United States,US,True,moderate,Private room,NaN,$696,NaN,7.0,12.0,3/27/2019
102054,Private Bedroom with Amazing Rooftop View,45936254757,verified,Trey,Brooklyn,Bushwick,40.69872,-73.92718,United States,US,False,flexible,Private room,NaN,$909,NaN,1.0,19.0,8/31/2017
102055,Pretty Brooklyn One-Bedroom for 2 to 4 people,23801060917,verified,Michael,Brooklyn,Bedford-Stuyvesant,40.67810,-73.90822,United States,US,True,moderate,Entire home/apt,NaN,$387,NaN,2.0,50.0,6/26/2019
102056,Room & private bathroom in historic Harlem,15593031571,unconfirmed,Shireen,Manhattan,Harlem,40.81248,-73.94317,United States,US,True,strict,Private room,NaN,$848,NaN,2.0,0.0,NaN
102057,Rosalee Stewart,93578954226,verified,Stanley,Manhattan,Harlem,40.81315,-73.94747,United States,US,False,flexible,Entire home/apt,2011.0,"$1,128",NaN,4.0,22.0,6/15/2019

In [34]:
data.isna()  # its going to return boolean True or False cellwise

,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
3,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102053,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False
102054,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False
102055,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False
102056,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,True
102057,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False

In [35]:
data.isna().sum()  # here we found that there is lot of NaN values in

Name                        250
host id                       0
host_identity_verified      289
host name                   404
neighbourhood group          29
neighbourhood                16
lat                           8
long                          8
country                     532
country code                131
instant_bookable            105
cancellation_policy          76
room type                     0
Construction year           214
price                       247
service fee                 273
minimum nights              400
number of reviews           183
last review               15832
dtype: int64

In [36]:
data.drop(columns=["last review"], inplace =True)  # its going to return boolean True or False cellwise

In [37]:
data.isna().sum()  # here we will not see column last review

Name                      250
host id                     0
host_identity_verified    289
host name                 404
neighbourhood group        29
neighbourhood              16
lat                         8
long                        8
country                   532
country code              131
instant_bookable          105
cancellation_policy        76
room type                   0
Construction year         214
price                     247
service fee               273
minimum nights            400
number of reviews         183
dtype: int64

In [38]:
# Now we are going to drop the NaN value rows.

data.dropna(inplace=True)

In [39]:
data.isna().sum()  # here we have now zero NaN

Name                      0
host id                   0
host_identity_verified    0
host name                 0
neighbourhood group       0
neighbourhood             0
lat                       0
long                      0
country                   0
country code              0
instant_bookable          0
cancellation_policy       0
room type                 0
Construction year         0
price                     0
service fee               0
minimum nights            0
number of reviews         0
dtype: int64

In [40]:
# 5. CLEANING INDIVIDUAL COLUMNS- i) lets say we want column values in this column host_identity_verified to be uppercase.

In [41]:
data

,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0
5,Large Cozy 1 BR Apartment In Midtown East,45498551794,verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,True,flexible,Entire home/apt,2013.0,$577,$115,3.0,74.0
7,BlissArtsSpace!,90821839709,unconfirmed,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,False,moderate,Private room,2009.0,"$1,060",$212,45.0,49.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102029,Cozy room in a 2B with backyard access,5155155913,unconfirmed,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,False,flexible,Private room,2018.0,$822,$164,1.0,9.0
102030,An East Williamsburg Delight,71564706996,verified,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,True,moderate,Private room,2015.0,$455,$91,4.0,36.0
102031,Cozy bedroom in williamsburg,83101851929,verified,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,True,flexible,Private room,2020.0,"$1,078",$216,1.0,58.0
102032,Spacious Room w/ 2 Bed,69037598918,unconfirmed,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,False,moderate,Private room,2007.0,$103,$21,7.0,40.0
102040,"Room in Queens, NY, near LGA.",56457739998,verified,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,True,strict,Private room,2022.0,$982,$196,1.0,239.0

In [42]:
data["host_identity_verified"]

0         unconfirmed
1            verified
4            verified
5            verified
7         unconfirmed
             ...
102029    unconfirmed
102030       verified
102031       verified
102032    unconfirmed
102040       verified
Name: host_identity_verified, Length: 99342, dtype: object

In [43]:
data["host_identity_verified"].str.upper()

0         UNCONFIRMED
1            VERIFIED
4            VERIFIED
5            VERIFIED
7         UNCONFIRMED
             ...
102029    UNCONFIRMED
102030       VERIFIED
102031       VERIFIED
102032    UNCONFIRMED
102040       VERIFIED
Name: host_identity_verified, Length: 99342, dtype: object

In [44]:
data["host_identity_verified"] = data["host_identity_verified"].str.upper()

In [45]:
data

,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews
0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0
1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0
5,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,True,flexible,Entire home/apt,2013.0,$577,$115,3.0,74.0
7,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,False,moderate,Private room,2009.0,"$1,060",$212,45.0,49.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102029,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,False,flexible,Private room,2018.0,$822,$164,1.0,9.0
102030,An East Williamsburg Delight,71564706996,VERIFIED,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,True,moderate,Private room,2015.0,$455,$91,4.0,36.0
102031,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,True,flexible,Private room,2020.0,"$1,078",$216,1.0,58.0
102032,Spacious Room w/ 2 Bed,69037598918,UNCONFIRMED,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,False,moderate,Private room,2007.0,$103,$21,7.0,40.0
102040,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,True,strict,Private room,2022.0,$982,$196,1.0,239.0

In [46]:
# 5. CLEANING INDIVIDUAL COLUMNS- ii)  column instant_bookable  - Let's say we are going to train a machine learning model & what we need to do 
# in machine learning model is we need to have numeric values for training the model so there's only True and False values.

In [47]:
data["instant_bookable"]

0         False
1         False
4         False
5          True
7         False
          ...
102029    False
102030     True
102031     True
102032    False
102040     True
Name: instant_bookable, Length: 99342, dtype: object

In [48]:
# we use apply() . it's going to go rowwise so i will say lamda X one  let's say it's going to be 1 if it is True and 0 for False 
data["instant_bookable"].apply( lambda  x:1 if x== True else 0 )

0         0
1         0
4         0
5         1
7         0
         ..
102029    0
102030    1
102031    1
102032    0
102040    1
Name: instant_bookable, Length: 99342, dtype: int64

In [49]:
# Explanation of above :
#The lambda keyword is used to create anonymous functions (functions without a name) in Python.
#The syntax for a lambda function is: lambda arguments: expression.
#In this case, x is the argument, and 1 if x == True else 0 is the expression that gets evaluated.
#The apply() method in pandas is used to apply a function (in this case, the lambda function) along the axis of a DataFrame or Series.
#In essence, this code iterates through the "instant_bookable" column of your data DataFrame. For each value (x) in that column,
#it checks if x is equal to True. 
#If it is, it returns 1; otherwise, it returns 0. The resulting series of 0s and 1s replaces the original "instant_bookable" column.

In [50]:
data

,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews
0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0
1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0
5,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,True,flexible,Entire home/apt,2013.0,$577,$115,3.0,74.0
7,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,False,moderate,Private room,2009.0,"$1,060",$212,45.0,49.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102029,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,False,flexible,Private room,2018.0,$822,$164,1.0,9.0
102030,An East Williamsburg Delight,71564706996,VERIFIED,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,True,moderate,Private room,2015.0,$455,$91,4.0,36.0
102031,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,True,flexible,Private room,2020.0,"$1,078",$216,1.0,58.0
102032,Spacious Room w/ 2 Bed,69037598918,UNCONFIRMED,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,False,moderate,Private room,2007.0,$103,$21,7.0,40.0
102040,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,True,strict,Private room,2022.0,$982,$196,1.0,239.0

In [51]:
#here above data is still showing True or False value in column instant_bookable . so we need to modify the above code.

In [52]:
data["instant_bookable"]= data["instant_bookable"].apply( lambda  x:1 if x== True else 0 )

In [53]:
data   # so here we can see now 0 and 1 in column instant_bookable

,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews
0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,strict,Private room,2020.0,$966,$193,10.0,9.0
1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0
5,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,1,flexible,Entire home/apt,2013.0,$577,$115,3.0,74.0
7,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,0,moderate,Private room,2009.0,"$1,060",$212,45.0,49.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102029,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,0,flexible,Private room,2018.0,$822,$164,1.0,9.0
102030,An East Williamsburg Delight,71564706996,VERIFIED,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,1,moderate,Private room,2015.0,$455,$91,4.0,36.0
102031,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,1,flexible,Private room,2020.0,"$1,078",$216,1.0,58.0
102032,Spacious Room w/ 2 Bed,69037598918,UNCONFIRMED,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,0,moderate,Private room,2007.0,$103,$21,7.0,40.0
102040,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,1,strict,Private room,2022.0,$982,$196,1.0,239.0

In [54]:
# To check its type here . In above data index is showing 0 1 4 5 7. we will use reset_index()

data.reset_index(inplace=True)

In [55]:
data

,index,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews
0,0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,strict,Private room,2020.0,$966,$193,10.0,9.0
1,1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0
2,4,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0
3,5,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,1,flexible,Entire home/apt,2013.0,$577,$115,3.0,74.0
4,7,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,0,moderate,Private room,2009.0,"$1,060",$212,45.0,49.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99337,102029,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,0,flexible,Private room,2018.0,$822,$164,1.0,9.0
99338,102030,An East Williamsburg Delight,71564706996,VERIFIED,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,1,moderate,Private room,2015.0,$455,$91,4.0,36.0
99339,102031,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,1,flexible,Private room,2020.0,"$1,078",$216,1.0,58.0
99340,102032,Spacious Room w/ 2 Bed,69037598918,UNCONFIRMED,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,0,moderate,Private room,2007.0,$103,$21,7.0,40.0
99341,102040,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,1,strict,Private room,2022.0,$982,$196,1.0,239.0

In [56]:
type(data["instant_bookable"][15])

numpy.int64

In [57]:
data

,index,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews
0,0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,strict,Private room,2020.0,$966,$193,10.0,9.0
1,1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0
2,4,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0
3,5,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,1,flexible,Entire home/apt,2013.0,$577,$115,3.0,74.0
4,7,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,0,moderate,Private room,2009.0,"$1,060",$212,45.0,49.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99337,102029,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,0,flexible,Private room,2018.0,$822,$164,1.0,9.0
99338,102030,An East Williamsburg Delight,71564706996,VERIFIED,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,1,moderate,Private room,2015.0,$455,$91,4.0,36.0
99339,102031,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,1,flexible,Private room,2020.0,"$1,078",$216,1.0,58.0
99340,102032,Spacious Room w/ 2 Bed,69037598918,UNCONFIRMED,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,0,moderate,Private room,2007.0,$103,$21,7.0,40.0
99341,102040,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,1,strict,Private room,2022.0,$982,$196,1.0,239.0

In [58]:
# 5. CLEANING INDIVIDUAL COLUMNS- iii)  Columns  Price and service fee -  they are strings and i want in integers

In [59]:
data["price"][15]  # here in output its a string . But i want integers  . also we here have space in the end . we need to remove that space

'$1,020 '

In [60]:
type(data["price"][15])  # here in output its a string )

str

In [61]:
data["price"]

0          $966
1          $142
2          $204
3          $577
4        $1,060
          ...
99337      $822
99338      $455
99339    $1,078
99340      $103
99341      $982
Name: price, Length: 99342, dtype: object

In [62]:
data["price"].str.replace("$","")  # so here in outpu below Dollar sign is removed and new series is formed in the format that we wanted.

0          966
1          142
2          204
3          577
4        1,060
          ...
99337      822
99338      455
99339    1,078
99340      103
99341      982
Name: price, Length: 99342, dtype: object

In [63]:
data["price"] = data["price"].str.replace("$","")

In [64]:
data["price"]

0          966
1          142
2          204
3          577
4        1,060
          ...
99337      822
99338      455
99339    1,078
99340      103
99341      982
Name: price, Length: 99342, dtype: object

In [65]:
data["price"] = data["price"].str.replace(",","")

In [66]:
data["price"]

0         966
1         142
2         204
3         577
4        1060
         ...
99337     822
99338     455
99339    1078
99340     103
99341     982
Name: price, Length: 99342, dtype: object

In [67]:
# to remove the space in the end
data["price"][15]

'1020 '

In [68]:
data["price"] = data["price"].str.replace(" ","")

In [69]:
# Lets see its data type. it should be integer.
type(data["price"][1])

str

In [70]:
# above still showing string. we need to integer data type. so, we use astype(int)
data["price"].astype(int) # output shows now int32 as datatype :)

0         966
1         142
2         204
3         577
4        1060
         ...
99337     822
99338     455
99339    1078
99340     103
99341     982
Name: price, Length: 99342, dtype: int32

In [71]:
type(data["price"].astype(int)[1])

numpy.int32

In [72]:
# so now we want above integer series in our original data frame

data["price"] = data["price"].astype(int)

In [73]:
type(data["price"][1])

numpy.int32

In [74]:
data.drop(columns=["index"], inplace =True )  # we want to remove index column

In [75]:
data # so here we won't have index columns in start

,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews
0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,strict,Private room,2020.0,966,$193,10.0,9.0
1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,moderate,Entire home/apt,2007.0,142,$28,30.0,45.0
2,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,moderate,Entire home/apt,2009.0,204,$41,10.0,9.0
3,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,1,flexible,Entire home/apt,2013.0,577,$115,3.0,74.0
4,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,0,moderate,Private room,2009.0,1060,$212,45.0,49.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99337,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,0,flexible,Private room,2018.0,822,$164,1.0,9.0
99338,An East Williamsburg Delight,71564706996,VERIFIED,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,1,moderate,Private room,2015.0,455,$91,4.0,36.0
99339,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,1,flexible,Private room,2020.0,1078,$216,1.0,58.0
99340,Spacious Room w/ 2 Bed,69037598918,UNCONFIRMED,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,0,moderate,Private room,2007.0,103,$21,7.0,40.0
99341,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,1,strict,Private room,2022.0,982,$196,1.0,239.0

In [76]:
# EXPORT THE DATA TO CSV FILES
#lETS SAY if i want to write this file to csv file to_csv()

data.to_csv("Cleaned Data.csv")

In [77]:
#Lets use pandas to read csv 

pd.read_csv("Cleaned Data.csv")

,Unnamed: 0,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews
0,0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,strict,Private room,2020.0,966,$193,10.0,9.0
1,1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,moderate,Entire home/apt,2007.0,142,$28,30.0,45.0
2,2,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,moderate,Entire home/apt,2009.0,204,$41,10.0,9.0
3,3,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,1,flexible,Entire home/apt,2013.0,577,$115,3.0,74.0
4,4,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,0,moderate,Private room,2009.0,1060,$212,45.0,49.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99337,99337,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,0,flexible,Private room,2018.0,822,$164,1.0,9.0
99338,99338,An East Williamsburg Delight,71564706996,VERIFIED,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,1,moderate,Private room,2015.0,455,$91,4.0,36.0
99339,99339,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,1,flexible,Private room,2020.0,1078,$216,1.0,58.0
99340,99340,Spacious Room w/ 2 Bed,69037598918,UNCONFIRMED,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,0,moderate,Private room,2007.0,103,$21,7.0,40.0
99341,99341,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,1,strict,Private room,2022.0,982,$196,1.0,239.0

In [78]:
data.to_csv("Cleaned_Data_wo_index.csv", index= False)

In [79]:
pd.read_csv("Cleaned_Data_wo_index.csv")

,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews
0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,strict,Private room,2020.0,966,$193,10.0,9.0
1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,moderate,Entire home/apt,2007.0,142,$28,30.0,45.0
2,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,moderate,Entire home/apt,2009.0,204,$41,10.0,9.0
3,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,1,flexible,Entire home/apt,2013.0,577,$115,3.0,74.0
4,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,0,moderate,Private room,2009.0,1060,$212,45.0,49.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99337,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,0,flexible,Private room,2018.0,822,$164,1.0,9.0
99338,An East Williamsburg Delight,71564706996,VERIFIED,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,1,moderate,Private room,2015.0,455,$91,4.0,36.0
99339,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,1,flexible,Private room,2020.0,1078,$216,1.0,58.0
99340,Spacious Room w/ 2 Bed,69037598918,UNCONFIRMED,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,0,moderate,Private room,2007.0,103,$21,7.0,40.0
99341,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,1,strict,Private room,2022.0,982,$196,1.0,239.0

In [80]:
# EXPORT THE DATA TO EXCEL FILES and if we don't want index column then we write index =False
data.to_excel("Excel_Cleaned_Data.xlsx", index= False)

In [ ]:
pd.read_excel("Excel_Cleaned_Data.xlsx")